### ISSUE TITLE
Forkerte Teller priser

### ISSUE THREAD

**Issue by Casper-O** [ulrikmoe/kortgebyr#15]
De priser der benyttes til at beregne Teller transaktionsgebyr på VISA/Mastercard må stamme fra Fysisk handel (Terminal) og ikke online betalinger. Dog er procent satsen i så fald også ved siden af, ud fra hvad der fremgår på følgende side:
https://www.nets.eu/dk/payments/vilkaar-og-priser/priser/

Nuværende beregning: 1.34% +  0,19 kr. | minimum 0,7kr

Korrekt beregning: 1.5% | minimum 0.7 kr

Overstående er ud fra diverse prislister der ligger ved eksempelvis epay, dog stammer prislisten fra 2015.

**Comment by ulrikmoe** [comment]
Tak for feedback. Priserne er taget fra deres prisudrenger, som kun kan tilgås hvis man logger ind (https://my.teller.com/login?&language=en).
![teller](https://cloud.githubusercontent.com/assets/1418021/20555965/21912fec-b165-11e6-91d1-f23188544965.png)

Hvis du har mulighed for det må du gerne selv prøve deres udregner og se om du får samme resultat.

**Comment by Casper-O** [comment]
Hej Ulrik.

Det lyder utroligt, især taget betragtning af jeg har fået priserne bekræftet af nogle med større omsætning end den estimeret omsætning du har oplyst på din teller konti

**Comment by ulrikmoe** [comment]
Hej Casper,

Hvis du har tid må du meget gerne selv prøve på https://apply.teller.com/landingpage?landingPageId=DK
