### ISSUE TITLE
New cost structure for Dankort

### ISSUE THREAD

**Issue by Thalch94** [ulrikmoe/kortgebyr#31]
Hej Kortgebyr.

Jeg er ved at oprette en aftale med NETS (fundet via jeres løsning), og jeg er i den forbindelse blevet gjort opmærksom på at der er kommet en ny gebyrstruktur hos Nets vedr. Dankort.
På hjemmesiden står den til først at blive aktiveret d. 1. Januar 2022, men priserne gælder fra dags dato (bekræftet ved telefonisk kontakt med Nets sælger). 
Vil i opdatere siden med de nye priser. Der er en væsentligt reduktion da der ikke længere er årsabonnement for at tage visa/mastercard.
https://assets.ctfassets.net/r8xjjnzwpfxs/75HESraLnfwGpCcV7PRGNQ/9d7b9066b142aa3a840d4fb33394aa62/Prisliste_Dankort_Oevrig_handel_01012022.pdf

**Comment by Thalch94** [comment]
Priser for internationale kort:
![image](https://user-images.githubusercontent.com/94870262/142933518-9f2470e3-392f-475b-85de-e484a13114aa.png)

**Comment by ulrikmoe** [comment]
Hej @Thalch94 

Tak for din feedback, og undskyld at jeg først vender tilbage nu. Jeg har opdateret priserne for Dankort, og sendt en ansøgning til Nets, for at få bekræftet de internationale priser du linker til. Nets priser har altid været svære at regne på, fordi de tager ekstra gebyr for kreditkort og firmakort, mens andre indløsere kører med et fast gebyr for alle korttyper. Derfor er vi nødt til at lave en fordelingsnøgle for firmakort og debet-/kreditkort. Det er noget jeg arbejder på :smile:
