### ISSUE TITLE
Shopify prisstigning

### ISSUE THREAD

**Issue by ThomasBNM** [ulrikmoe/kortgebyr#36]
Hej, er det muligt at få opdateret alle mulige priser? F.eks. shopify abb er også off (der vises kun prisen på årligt abb og ikke de nye månedelige priser) Jeg findet det ENORMT svært at gennemskue, hvilken løsning der er bedste - så alle der der "tillægs" priser fra f.eks. Shopify når der bruges 3. parts løsninger, kan det ikke blive medregnet også? Vil sætte stor pris på det :)

**Comment by ulrikmoe** [comment]
Hej Thomas,
Mange tak for din feedback. Vi havde rigtigt nok overset Shopifys prisstigning, men det er nu tilføjet :)
